# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-31 00:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bangazon_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ('customer',)},
        ),
        migrations.AlterModelOptions(
            name='productorder',
            options={'ordering': ('order',)},
        ),
        migrations.RenameField(
            model_name='order',
            old_name='user_id',
            new_name='customer',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='payment_method_id',
            new_name='payment_method',
        ),
        migrations.RenameField(
            model_name='paymentmethod',
            old_name='user_id',
            new_name='customer',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='product_category_id',
            new_name='product_category',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='user_id',
            new_name='seller',
        ),
        migrations.RenameField(
            model_name='productorder',
            old_name='order_id',
            new_name='order',
        ),
        migrations.RenameField(
            model_name='productorder',
            old_name='product_id',
            new_name='product',
        ),
    ]
