# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-26 01:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bangazon_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productcategory',
            options={'ordering': ('name',)},
        ),
    ]
