# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-27 18:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bangazon_api', '0003_order_created'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='UserProfile',
        ),
    ]
