# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-30 15:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bangazon_api', '0005_userstaff'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserStaff',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='date_of_birth',
            field=models.DateField(default=False),
        ),
    ]
