# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-30 16:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Bangazon_api', '0006_auto_20170130_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='Bangazon_api.UserProfile'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_category_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='Bangazon_api.ProductCategory'),
        ),
        migrations.AlterField(
            model_name='product',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='Bangazon_api.UserProfile'),
        ),
    ]
