# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-30 16:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Bangazon_api', '0007_auto_20170130_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='Bangazon_api.PaymentMethod'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_methods', to='Bangazon_api.UserProfile'),
        ),
        migrations.AlterField(
            model_name='productorder',
            name='order_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_orders', to='Bangazon_api.Order'),
        ),
        migrations.AlterField(
            model_name='productorder',
            name='product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_orders', to='Bangazon_api.Product'),
        ),
    ]
